giphy api
artepepep/proj_homeworks pull request #4
Opened 2023-09-02 13:31 UTC by artepepep

2023-09-02 20:27 UTC, bielanm requested changes

2023-09-02 20:27 UTC, bielanm commented on homework_11/giphy_app.py
> +GIPHY_KEY = 'AhV2XU87boO7jvHdWnjmMxRLByk3oSUP'
API ключі неможна комітити, бо хтось його знайте у відкритому доступі і з тебе потім гроші знімуть. Його треба або читати з файлу, або задавати змінною оточення

2023-09-03 10:46 UTC, artepepep commented on homework_11/giphy_app.py
> +GIPHY_KEY = 'AhV2XU87boO7jvHdWnjmMxRLByk3oSUP'
зараз перероблю

2023-09-03 10:54 UTC, artepepep commented on homework_11/giphy_app.py
> +GIPHY_KEY = 'AhV2XU87boO7jvHdWnjmMxRLByk3oSUP'
можете допомогти, типу треба спочатку новий файл створити з ключом а потім імпортувати з нього функцію з цим ключем ?

2023-09-03 11:00 UTC, artepepep commented on homework_11/giphy_app.py
> +GIPHY_KEY = 'AhV2XU87boO7jvHdWnjmMxRLByk3oSUP'
![image](https://github.com/artepepep/proj_homeworks/assets/37035794/0b7e50d9-1afa-411e-9208-4e0adfca2fbd)

в мене чомусь таку помилку видає

2023-09-03 15:46 UTC, artepepep commented on homework_11/giphy_app.py
> +GIPHY_KEY = 'AhV2XU87boO7jvHdWnjmMxRLByk3oSUP'
зробив

2023-09-04 10:12 UTC, bielanm requested changes
Мається на увазі що код треба було залишити таким був, але створити (і не комітити) текстовий файли `giphy_apikey.txt` і в коді зчитувати його за допомогою with open() as fin: fin.read().

і файли/функції намагайся одразу називати згідно відповідності коду, бо зараз в тебе data.py (що це взагалі таке), program, etc...

2023-09-04 11:49 UTC, artepepep commented
зараз тоді все зроблю

2023-09-04 14:43 UTC, bielanm requested changes

2023-09-04 14:43 UTC, bielanm commented on homework_11/data_1.py
Ось цей файл ще треба видалити

2023-09-04 19:46 UTC, artepepep commented on homework_11/data_1.py
dobre

2023-09-06 12:12 UTC, bielanm approved these changes

2023-09-17 11:06 UTC, merged